import { NextResponse } from 'next/server';

const projectsData = [
  { id: 1, title: "Event Highlight JA.SE.KA Reels", category: "Video Editing", video: "/jaseka.mp4", description: "Produced and edited a promotional video for the 'Jalan Sehat' community event, successfully increasing local engagement through dynamic visuals and storytelling.", role: "Chairman Karang Taruna RW 01"
     },
  { id: 2, title: "Unasradio Official Web", category: "Web & App", image: "/unasradio1.png", images: ["/unasradio1.png","/unasradio2.png","/unasradio3.png","/unasradio4.png","/unasradio5.png","/unasradio6.png","/unasradio7.png","/unasradio8.png","/unasradio9.png"], 
    description: "The primary digital platform for Unasradio, designed to facilitate live online broadcasting and showcase program schedules.", role: "Front-End Developer" },
  { 
    id: 13, title: "Event Highlight JA.SE.KA part 2 Reels", category: "Video Editing", video: "/jaseka2.mp4", description: "Produced and edited a promotional video for the 'Jalan Sehat' part 2 community event, successfully increasing local engagement through dynamic visuals and storytelling.", role: "Video Editor"
     },
  { id: 4, title: "Cyber Security Seminar", 
    category: "Public Speaker",
     image: "/mcseminarcyber1.png", 
     images: ["/mcseminarcyber1.png","/mcseminarcyber2.png"],
     description: "Served as the main moderator for an intensive Cyber Security Seminar hosted by Karang Taruna Cilandak Barat.", 
     role: "Moderator" },
  { id: 5, title: "Comparative Study Event", category: "Public Speaker", image: "/mcupn.png", images: ["/mcupn.png","/mcupn1.png","/mcupn2.png"], description: "Acted as the Master of Ceremony for the collaborative comparative study event between Unasradio and Fortyfive UPN.", role: "Master of Ceremony" },
  { id: 6,
     title: "Moderator Seminar & Workshop UnasRadio", 
     category: "Public Speaker", 
     image: "/moderator-seminar-workshop.png", 
     images:["/moderator-seminar-workshop.png","/moderator-seminar-workshop2.png","/moderator-seminar-workshop3.png"],
     description: "Served as the Moderator for Unasradio's Broadcasting Seminar & Workshop, facilitating insightful discussions between industry experts and participants.",
      role: "Vice Head of Division Creative UnasRadio" },
  { id: 7, title: "Story Frame Pelatihan & Sharing Session Unas Radio", category: "Design", image: "/storyframepelatihanradio.png", description: "Redesigned the core visual identity and social media templates for Unasradio", role: "Vice Head of Division Creative UnasRadio" },
  { id: 8, title: "Banner Paskibra Bumantara", category: "Design", image: "/Banner_aangggggg.jpg", description: "Designed a professional event banner for Paskibra Bumantar, focusing on visual impact and organizational branding.", role: "Freelance Graphic Designer" },
  { id: 9, title: "Instagram Feedss Bracelet Store", category: "Design", image: "/BRACELET.jpg", images: ["/BRACELET.jpg", "/GELANG COUPLE.jpg"], description: "Visual Branding: Instagram Feed Design for a Handmade Bracelet Business.", role: "Freelance Graphic Designer" },
  { id: 10, title: "JIB airlines logo (personal project)", category: "Design", image: "/JIB airlines.png", description: "Brand Identity Design: Concept Logo for an Airline Ticketing Service (Academic Project).", role: "Freelance Graphic Designer" },
  { id: 11, title: "Cover Podcast Spotify Kisah Kasih Krisis", category: "Design", image: "/kkk.png", description: "Visual Identity: Podcast Cover Art for 'Kisah Kasih Krisis' (Stories of Love & Crisis).", role: "Vice Head of Division Creative UnasRadio" },
  { id: 12, title: "Islamic Resource & Prayer App", 
    category: "Web & App", 
    image: "/aplikasirawi.png", 
    images: ["/aplikasirawi.png", "/aplikasirawi2.png","/aplikasirawi3.png","/aplikasirawi4.png","/aplikasirawi5.png","/aplikasirawi6.png"], 
    description: "A comprehensive mobile application providing accurate prayer schedules and a rich library of Islamic literature including Simtuddurror, Barzanji, and Diba'.", role: "Mobile Developer" },
  { id: 3, title: "Rentashot Platform", category: "Web & App", image: "/rentashot1.png", images: ["/rentashot1.png","/rentashot2.png","/rentashot3.png","/rentashot4.png","/rentashot5.png","/rentashot6.png","/rentashot7.png","rentashot8.png"], description: "A specialized digital platform built for a photography equipment rental service with a seamless booking flow.", role: "Web Developer" },
  { id: 14, title: "Agility Wear", 
    category: "Web & App",
     image: "/agility1.png", 
     images: ["/agility1.png","/agility2.png","/agility3.png","/agility4.png","/agility5.png","/agility6.png","/agility7.png","/agility8.png","/agility9.png","/agility10.png"],
     description: "Agility Wear Web Project: A custom-built web application designed for browsing and purchasing athletic equipment.", 
     role: "Personal Project" },
     { id: 15, title: "Logeeka Dashboard", 
    category: "Web & App",
     image: "/logeeka.png", 
     images: ["/logeeka2.png","/logeeka3.png","/logeeka4.png","/logeeka5.png","/logeeka6.png","/logeeka7.png","/logeeka8.png","/logeeka9.png"],
     description: "Logeeka Internal Systems: Admin Dashboard Development & Optimization.", 
     role: "Website Developer" },
     { id: 16, title: "Poster Maulid Nabi Muhammad SAW", 
    category: "Design",
     image: "/MAULID NABI MUHAMMAD SAW.jpg", 
     description: "Designed an official poster for the Maulid Nabi Muhammad SAW (The Birthday of Prophet Muhammad) celebration, focusing on respectful and elegant aesthetics", 
     role: "Freelanc Graphic Design" },
     { id: 17, title: "Feeds Instagram Open Recruitment UnasRadio", 
    category: "Design",
     image: "/oprecradio.jpg", 
     description: "Designed an official poster for the Maulid Nabi Muhammad SAW (The Birthday of Prophet Muhammad) celebration, focusing on respectful and elegant aesthetics", 
     role: "Vice Head of Division Creative UnasRadio" },
      { id: 18, title: "Feeds Instagram Open Recruitment UnasRadio", 
    category: "Design",
     image: "/open recruitmnt.jpg", 
     description: "Designed a professional and authoritative visual identity for Paskibra Bumantara's recruitment campaign, focusing on patriotic and discipline-oriented visual storytelling.", 
     role: "Freelance Graphic Designer" },
      { id: 19, title: "Poster Topeng Alam", 
    category: "Design",
     image: "/Poster Digital_Topeng Alam_Universitas Nasional_page-0001.jpg", 
     description: "Designed a powerful and atmospheric movie poster for the short film competition entry 'Topeng Alam' (Nature's Mask), conceptually blending local folklore elements with the urgency of flora conservation.", 
     role: "Graphic Designer" },
      { id: 20, title: "Poster Kemerdekaan", 
    category: "Design",
     image: "/posterkemerdekaan.png", 
     description: "Designed a powerful and atmospheric movie poster for the short film competition entry 'Topeng Alam' (Nature's Mask), conceptually blending local folklore elements with the urgency of flora conservation.", 
     role: "Graphic Designer" },
     {  id: 21, 
      title: "Master of Ceremony Traning Camp Karang Taruna Cilandak Barat", 
    category: "Public Speaker",
     image: "/mc training camp Karang Taruna Cilandak Barat.png", 
     images: ["/mc training camp Karang Taruna Cilandak Barat.png","/mckatarcilbar.png"],
     description: "Logeeka Internal Systems: Admin Dashboard Development & Optimization.", 
     role: "Master of Ceremony" },
     {  id: 22, 
      title: "Chairman Karang Taruna RW 01 ", 
    category: "Event Management",
     image: "/katar.png", 
     images: ["/katar.png","/katar2.png","/katar3.png","/katar4.png"],
     description: "Chairman of Karang Taruna (Youth Organization) RW 01, leading organizational strategic planning and community development initiatives for local youth.", 
     role: "Chairman" },
      {  id: 23, 
      title: "Vice Head pf Division Creative Unas Radio ", 
    category: "Event Management",
     image: "/kreatip.png", 
     images: ["/kreatip.png","/kreatip2.png","/kreatip3.png","/kreatip4.png"],
     description: "Vice Head of Creative Division at Unasradio, overseeing the visual identity and creative strategy for all media platforms and organizational branding.", 
     role: "Vice Head pf Division Creative Unas Radio" },
      {  id: 24, 
      title: "Head of Da'wah Division IRMALA ", 
    category: "Event Management",
     image: "/irmalad.png", 
     images: ["/irmalad.png","/irmalad2.png","/irmalad3.png","/irmalad4.png"],
     description: "Head of the Da'wah Division at IRMALA, responsible for planning and executing religious education programs and community outreach initiatives.", 
     role: "Head of Da'wah Division IRMALA" },
     {  id: 25, 
      title: "Public Relations UNAS FEST 2025 ", 
    category: "Event Management",
     image: "/pr.png", 
     images: ["/pr.png","/pr2.png","/pr3.png","/pr4.png"],
     description: "Served as a Public Relations Officer for Unasfest, managing external communications and building strategic partnerships to enhance the festival's visibility.", 
     role: "Head of Da'wah Division IRMALA" },
      {  id: 26, 
      title: "Gema RAMADHAN iRMALA  ", 
    category: "Video Editing",
     video: "/gema.mp4", 
     description: "Served as a Public Relations Officer for Unasfest, managing external communications and building strategic partnerships to enhance the festival's visibility.", 
     role: "Head of Da'wah Division IRMALA" },
];



export async function GET() {
  return NextResponse.json({
    status: "success",
    message: "Data portofolio berhasil diambil!",
    data: projectsData
  });
}